const review_based_on_emotion = {
  angry: [
    "Ugh, this pic is infuriating!",
    "Seriously? This pic makes me so angry!",
    "Oh great, this pic just gets under my skin!",
    "Well, isn't this pic just frustrating!",
    "Oh wonderful, this pic makes me really mad!",
    "Really? This pic is making my blood boil!",
    "Whoops, this pic is really ticking me off!",
    "Oh, fantastic, this pic is just infuriating!",
    "Oh come on, this pic is seriously annoying!",
    "Fantastic, this pic is really getting on my nerves!",
    "Oh, thanks a lot, this pic is making me furious!",
    "Oh for goodness sake, this pic is just aggravating!",
    "Gosh, I can't believe how mad this pic makes me!",
    "Oops, thanks a bunch, this pic is really irritating!",
    "Well, isn't that just great, this pic is really frustrating!",
    "Oh wow, congratulations, this pic is making me seethe!",
    "Phew, talk about a source of anger, this pic really does it!",
    "Oh boy, thanks a bunch, this pic is just infuriating!",
    "Yikes, this pic is definitely fueling my anger!",
    "Whoa, I definitely wasn't prepared for how mad this pic would make me!",
  ],
  disgust: [
    "Ugh, this pic is absolutely revolting!",
    "Seriously? This pic makes me want to gag!",
    "Oh, blegh, this pic is so disgusting!",
    "Well, isn't this pic just nauseating!",
    "Oh, gross, this pic makes me want to vomit!",
    "Ew, this pic is making me feel sick!",
    "Whoops, this pic is making me queasy!",
    "Yuck, this pic is absolutely repulsive!",
    "Oh, great, this pic is making me feel disgusted!",
    "Oh, wonderful, this pic is truly nauseating!",
    "Oh, thanks a lot, this pic is making me feel repulsed!",
    "Oh, for goodness sake, this pic is just making me feel ill!",
    "Gosh, I can't believe how disgusting this pic is!",
    "Oops, thanks a bunch, this pic is truly gross!",
    "Well, isn't that just great, this pic is making me want to throw up!",
    "Oh wow, congratulations, this pic is making me feel absolutely sickened!",
    "Phew, talk about a stomach-turner, this pic really hits the mark!",
    "Oh boy, thanks a bunch, this pic is just absolutely vile!",
    "Yikes, this pic is definitely making me feel repelled!",
    "Whoa, I definitely wasn't prepared for how disgusting this pic would be!",
  ],
  fear: [
    "Ugh, that pic gave me quite a fright!",
    "Seriously? My heart skipped a beat there with that pic!",
    "Yikes, that pic definitely startled me!",
    "Well, wasn't that pic unexpected!",
    "Oh great, that pic caught me off guard!",
    "Really? That pic was a bit startling!",
    "Whoops, nearly jumped out of my skin with that pic!",
    "Oh wonderful, that pic was a surprise!",
    "Oh come on, that pic was a bit alarming!",
    "Fantastic, that pic gave me a moment of panic!",
    "Oh, thanks a lot, that pic definitely made me jump!",
    "Oh for goodness sake, that pic was a bit hair-raising!",
    "Gosh, I wasn't expecting that pic!",
    "Oops, thanks a bunch, that pic definitely startled me!",
    "Well, isn't that just great, that pic was a bit nerve-wracking!",
    "Oh wow, congratulations, that pic was quite a shock!",
    "Phew, talk about a sudden scare with that pic!",
    "Oh boy, thanks a bunch, that pic definitely made my heart race!",
    "Yikes, that pic was definitely a surprise!",
    "Whoa, I definitely wasn't prepared for that pic!",
  ],
  happy: [
    "Your photo is really cool, who clicked it",
    "Wow, this photo is amazing! Great job!",
    "Love this shot! Absolutely stunning!",
    "This photo is stunning! Such a beautiful capture!",
    "Incredible shot! You have a real talent!",
    "Absolutely beautiful! Such a fantastic photo!",
    "Wow, this is fantastic! Really impressive work!",
    "This is such a cool photo! Love it!",
    "Love the composition! Very well done!",
    "Amazing capture! Truly breathtaking!",
    "Such a great photo! Really impressive!",
    "So creative! Love the creativity in this!",
    "Absolutely stunning! Really impressive work!",
    "This shot is incredible! Love the perspective!",
    "Love this picture! Great work!",
    "Beautiful photo! Really well done!",
    "Really cool shot! Love the style!",
    "Fantastic capture! Very impressive!",
    "Such a great photo! Love the vibe!",
    "This picture is awesome! Great job!",
  ],
  neutral: [
    "Interesting composition in this photo.",
    "This picture offers a unique perspective.",
    "A curious detail captured in this image.",
    "Noticed an intriguing element in this photo.",
    "Interesting choice of subject in this picture.",
    "A subtle nuance caught in this image.",
    "Captured an unusual moment in this photo.",
    "Interesting interplay of light and shadow.",
    "A thought-provoking aspect in this picture.",
    "A curious observation in this photo.",
    "This picture prompts reflection.",
    "Noticed an interesting feature in this image.",
    "An unusual angle captured in this photo.",
    "A detail worth pondering in this picture.",
    "This photo offers a different perspective.",
    "A unique moment captured in this image.",
    "Interesting textures in this photo.",
    "A moment of quiet observation in this picture.",
    "An intriguing element adds depth to this photo.",
    "This image invites contemplation.",
  ],
  sad: [
    "This picture makes me contemplative, evoking deep emotions.",
    "Such a poignant image, it brings a sense of melancholy.",
    "This picture fills me with nostalgia, remembering simpler times.",
    "A haunting image, it stirs up feelings of sorrow.",
    "This picture is bittersweet, reminding me of both joy and sadness.",
    "An emotionally charged photo, it elicits a sense of empathy.",
    "This image evokes a sense of longing, a yearning for something lost.",
    "A touching portrayal, it brings tears to my eyes.",
    "This picture captures the essence of heartache, resonating deeply.",
    "An emotive image, it tugs at the heartstrings.",
    "This photo radiates warmth, comforting in its sadness.",
    "A powerful depiction, it echoes the pain of loss.",
    "This image speaks volumes, conveying a sense of profound sadness.",
    "A thought-provoking photo, it prompts reflection on life's struggles.",
    "This picture is heartrending, stirring up a mix of emotions.",
    "An evocative image, it captures the rawness of human emotions.",
    "This photo is deeply moving, leaving a lasting impression.",
    "A soulful portrayal, it speaks to the depths of the human experience.",
    "This picture is poignant, resonating with feelings of sorrow.",
    "An expressive image, it communicates a sense of profound sadness.",
  ],
  surprise: [
    "Wow, this picture caught me off guard! So unexpected and utterly delightful!",
    "I didn't see this coming! This photo is full of surprises, and it's making me smile!",
    "What a surprise! This picture is unlike anything I've seen before, and it's filling me with wonder!",
    "I'm pleasantly surprised by this photo! It's truly remarkable, and it's warming my heart!",
    "Well, I didn't expect that! This picture is a delightful surprise, and it's making me feel joyous!",
    "Surprise, surprise! This photo is a real gem, and it's lifting my spirits!",
    "I'm taken aback by this image! Such a pleasant surprise, and it's making me feel excited!",
    "This picture is a wonderful surprise! It's truly captivating, and it's giving me a sense of awe!",
    "Whoa, talk about unexpected! This photo is a pleasant surprise, and it's making me feel amazed!",
    "This photo took me by surprise! It's absolutely stunning, and it's leaving me in awe!",
    "I'm surprised by the beauty of this picture! It's breathtaking, and it's filling me with admiration!",
    "Well, this is a pleasant surprise! What an incredible photo, it's truly moving!",
    "This picture is a delightful surprise! It's truly remarkable, and it's making me feel touched!",
    "I'm pleasantly surprised by the quality of this photo! It's outstanding, and it's making me feel impressed!",
    "What a pleasant surprise! This picture is absolutely captivating, and it's stirring my emotions!",
    "This photo is a surprise in the best way possible! It's stunning, and it's evoking strong feelings in me!",
    "This picture is full of surprises! It's truly remarkable, and it's making me feel inspired!",
    "Well, color me surprised! This photo is truly exceptional, and it's giving me a sense of gratitude!",
    "This photo is a wonderful surprise! It's truly captivating, and it's filling me with happiness!",
    "Surprise, surprise! This picture is truly extraordinary, and it's making me feel deeply moved!",
  ],
};

export default review_based_on_emotion;
